project-includes = ["."]
project-excludes = ["**/.[!/.]*", "**/tests"]
search-path = ["."]
site-package-path = [".venv/lib/site-packages"]

python-platform = "linux"
python-version = "3.12"
python-interpreter = ".venv/scripts/python"

replace-imports-with-any = [
  "sympy.*",
  "*.series",
]
ignore-errors-in-generated-code = true
use-untyped-imports = true
ignore-missing-source = true

# disable `bad-assignment` and `invalid-argument` for the whole project
[errors]
bad-assignment = false
invalid-argument = false
